apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-engine-mongodb.connectionSecretName" . }}
  namespace: {{ include "agent-engine-mongodb.namespace" . }}
  labels:
    app.kubernetes.io/name: mongodb
    {{- include "agent-engine-mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ include "agent-engine-mongodb.connectionString" . | quote }}
