{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-engine-infra.mongodbAuthSecretName" . }}
  namespace: {{ include "agent-engine-infra.namespace" . }}
  labels:
    app.kubernetes.io/name: mongodb
    {{- include "agent-engine-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mongodb.auth.usernameKey }}: {{ .Values.mongodb.auth.username | quote }}
  {{ .Values.mongodb.auth.passwordKey }}: {{ .Values.mongodb.auth.password | quote }}
{{- end }}
