apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-engine-infra.fullname" . }}-mongodb-connection
  namespace: {{ include "agent-engine-infra.namespace" . }}
  labels:
    app.kubernetes.io/name: mongodb
    {{- include "agent-engine-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ include "agent-engine-infra.mongodbConnectionString" . | quote }}
