{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.serviceName }}
  namespace: {{ include "agent-engine-infra.namespace" . }}
  labels:
    app.kubernetes.io/name: mongodb
    {{- include "agent-engine-infra.labels" . | nindent 4 }}
  {{- with .Values.mongodb.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mongo
      port: {{ .Values.mongodb.port }}
      targetPort: mongo
{{- end }}
