 {{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-engine-infra.postgresSecretName" . }}
  namespace: {{ include "agent-engine-infra.namespace" . }}
  labels:
    app.kubernetes.io/name: postgres
    {{- include "agent-engine-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.usernameKey }}: {{ .Values.postgres.username | quote }}
  {{ .Values.postgres.passwordKey }}: {{ .Values.postgres.password | quote }}
{{- end }}
