{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agent-engine.app-base.instance" . }}
  namespace: {{ include "agent-engine.app-base.namespace" . }}
  labels:
    {{- include "agent-engine.app-base.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "agent-engine.app-base.instance" $ }}
                port:
                  number: {{ $.Values.service.httpPort }}
          {{- end }}
    {{- end }}
{{- end }}
