apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-engine-runtime.fullname" . }}
  namespace: {{ include "agent-engine-runtime.namespace" . }}
  labels:
    {{- include "agent-engine-runtime.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agent-engine-runtime.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
