plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.catalog'

dependencies {
    api project(':tenancy:api')
    implementation project(':util:ms:client')
    api project(':util:infra')
    implementation project(':util:common')
    implementation project(':util:tenancy')
    implementation project(':util:context')
    implementation project(':util:agents')
    implementation project(':util:distributed')

    compileOnly libs.jakarta.inject.api
    compileOnly libs.jakarta.enterprise.cdi.api

}
