subprojects {
    repositories {
        mavenCentral()
    }
}

tasks.register('build') {
    dependsOn ':engine:build', ':interfaces:cli:build', ':interfaces:rest:build'
}

tasks.register('test') {
    dependsOn ':engine:test', ':interfaces:cli:test', ':interfaces:rest:test'
}

tasks.register('restDev') {
    dependsOn ':interfaces:rest:quarkusDev'
}

tasks.register('syncPlugins', Copy) {
    dependsOn ':engine:jar'
    from('plugins') {
        include '**/build/libs/*.jar'
    }
    into('plugins')
}
