plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'agent-engine'

include 'runtime'

include 'runtime:api'

include 'core:api'

include 'core'

include 'connectors:core'

include 'interfaces:rest'

include 'util:common'

include 'util:mongodb'

include 'util:ms'

include 'util:ms:client'

include 'util:agents'

include 'util:pekko'
