plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'agent-engine'

include 'catalog:api'
include 'catalog:core'

include 'interfaces:rest'

include 'tenancy'

include 'agent:api'
include 'agent:infra'
include 'agent:core'
include 'agent:jobs'

include 'connectors:api'
include 'connectors:infra'
include 'connectors:http'
include 'connectors:core'

include 'util:infra'
include 'util:mongodb'
include 'util:vectordb'
include 'util:sql'
include 'util:crypto'
include 'util:cloudstorage'
include 'util:ms:client'
include 'util:ms:server'
include 'util:agents'
include 'util:models'
include 'util:pekko'
include 'util:scripts'
include 'util:common'
include 'util:context'
include 'util:distributed'

include 'knowledge:api'
include 'knowledge:core'
include 'knowledge:jobs'

include 'chaos:api'
include 'chaos:core'

include 'internal'

include 'scheduler:api'
include 'scheduler:core'