plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'agent-engine'

include 'engine'
include 'engine:api'
include 'engine:plugin'
include 'util'
include 'util:common'
include 'util:mongodb'
include 'util:ms'
include 'connectors'
include 'connectors:core'
include 'interfaces'
include 'interfaces:rest'
include 'interfaces:local'
