namespace: agent-engine
nameOverride: ""
fullnameOverride: ""

commonLabels: {}
imagePullSecrets: []

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "7.0"
    digest: ""
    pullPolicy: IfNotPresent
  serviceName: mongodb
  port: 27017
  connectionString: ""
  auth:
    enabled: false
    username: agentengine
    password: agentengine
    existingSecret: ""
    usernameKey: username
    passwordKey: password
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: ""
  service:
    annotations: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  probes:
    readiness:
      periodSeconds: 10
      failureThreshold: 6
      timeoutSeconds: 5
    liveness:
      periodSeconds: 20
      failureThreshold: 6
      timeoutSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    digest: ""
    pullPolicy: IfNotPresent
  serviceName: postgres
  port: 5432
  jdbcUrl: ""
  database: agent_engine_events
  username: agentengine
  password: agentengine
  existingSecret: ""
  usernameKey: username
  passwordKey: password
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: ""
  service:
    annotations: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  probes:
    readiness:
      periodSeconds: 10
      failureThreshold: 6
      timeoutSeconds: 5
    liveness:
      periodSeconds: 20
      failureThreshold: 6
      timeoutSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}
