plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation project(':util:common')

    api libs.ag.ui.core

    implementation libs.microprofile.openapi.api
    implementation libs.mongodb.bson
    implementation libs.google.adk.langchain4j
    implementation libs.google.genai
    implementation libs.jakarta.validation.api
    implementation libs.jakarta.enterprise.cdi.api
    implementation libs.slf4j.api
}