apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ include "agent-engine-localstack.namespace" . }}
  labels:
    app.kubernetes.io/name: localstack
    {{- include "agent-engine-localstack.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: gateway
      port: {{ .Values.port }}
      targetPort: gateway
