plugins {
    id 'jacoco'
    id 'com.agentengine.java-library-conventions'
    alias(libs.plugins.quarkus)
}

dependencies {
    api project(':engine:api')

    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation platform(libs.langchain4j.bom)
    implementation libs.slf4j.api
    implementation libs.langchain4j.core
    implementation libs.langchain4j.open.ai
    implementation libs.langchain4j.ollama
    implementation libs.quarkus.mongodb.client
    implementation libs.google.adk.langchain4j
    implementation libs.vertx.json.schema
    implementation 'io.quarkus:quarkus-smallrye-fault-tolerance'

    testImplementation libs.quarkus.junit5
    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
}

tasks.jacocoTestReport {
    dependsOn tasks.test
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.test {
    finalizedBy tasks.jacocoTestReport
}
