plugins {
    id 'jacoco'
    id 'com.agentengine.java-library-conventions'
    alias(libs.plugins.quarkus)
}

dependencies {
    api project(':engine:api')
    implementation project(':engine:plugin')
    implementation project(':connectors:core')
    implementation project(':util:common')
    implementation project(':util:mongodb')
    implementation project(':util:ms')

    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation platform(libs.langchain4j.bom)
    implementation libs.slf4j.api
    implementation libs.langchain4j.core
    implementation libs.langchain4j.open.ai
    implementation libs.langchain4j.ollama
    implementation libs.quarkus.mongodb.client
    implementation libs.google.adk.langchain4j
    implementation libs.vertx.json.schema
    implementation libs.quarkus.smallrye.fault.tolerance
    implementation libs.quarkus.jackson
    implementation libs.quarkus.arc
    implementation libs.quarkus.hibernate.validator
    implementation libs.quarkus.opentelemetry
    implementation libs.guava
    implementation libs.stateless4j

    testImplementation libs.quarkus.junit5
    testImplementation libs.quarkus.junit5.mockito
    testImplementation libs.assertj.core
    testImplementation libs.mockito.junit.jupiter
    testImplementation libs.grpc.testing

    integrationTestImplementation libs.quarkus.junit5
    integrationTestImplementation libs.assertj.core
    integrationTestImplementation libs.testcontainers.junit.jupiter
    integrationTestImplementation libs.testcontainers.mongodb
    integrationTestImplementation libs.testcontainers.redis
}

tasks.jacocoTestReport {
    dependsOn tasks.test
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.test {
    finalizedBy tasks.jacocoTestReport
}
