plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('../../engine/build/libs/engine.jar')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

final def pluginJarName = 'echo-agent-plugin'

tasks.named('jar') {
    archiveBaseName.set(pluginJarName)
}
