plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('../../engine/build/libs/engine.jar')
    implementation files('../../engine/api/build/libs/api.jar')
    implementation 'com.alibaba.fastjson2:fastjson2:2.0.48'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

final def pluginJarName = 'echo-agent-plugin'

tasks.named('jar') {
    archiveBaseName.set(pluginJarName)
}
