plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation platform(libs.quarkus.bom)

    implementation project(':util:common')

    implementation project(':util:context')
    implementation project(':util:distributed')
    implementation project(':util:infra')
    implementation project(':util:crypto')
    api libs.mongodb.driver.sync

    implementation libs.quarkus.mongodb.client
    implementation libs.slf4j.api
    implementation libs.guava

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
