plugins {
    id 'com.agentengine.java-library-conventions'
    alias(libs.plugins.protobuf)
}

dependencies {
    implementation project(':util:common')
    implementation project(':util:mongodb')
    implementation libs.mongodb.driver.sync
    implementation libs.grpc.stub
    implementation libs.grpc.protobuf
    implementation libs.protobuf.java
    implementation libs.annotations.api
    implementation libs.jakarta.inject.api
    implementation libs.jakarta.enterprise.cdi.api

    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation libs.quarkus.arc
    implementation libs.quarkus.grpc
    implementation libs.rxjava
    implementation libs.slf4j.api

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${libs.versions.protobuf.get()}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${libs.versions.grpc.get()}"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}
