plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.knowledge'

dependencies {
    implementation project(':util:common')
    implementation project(':util:tenancy')
    implementation project(':util:vectordb')
    implementation project(':util:agents')
    api project(':tenancy:api')
    implementation project(':util:ms:client')
    api project(':util:infra')
    compileOnly libs.jakarta.inject.api
}
