syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.agentengine.util.ms.grpc";
option java_outer_classname = "ServiceProto";

package com.agentengine.util.ms.grpc;

message Request {
  string service = 1;
  string method = 2;
  bytes payload = 3; // JSON Array of arguments
  bytes context = 4; // JSON-encoded com.agentengine.util.common.context.Context, if known
}

message Response {
  bytes payload = 1; // JSON result
}

service Service {
  rpc execute(Request) returns (stream Response);
}
