namespace: agent-engine

image:
  repository: localstack/localstack
  tag: "3"
  pullPolicy: IfNotPresent

serviceName: localstack
port: 4566
services: s3
region: us-east-1

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 100m
    memory: 512Mi

imagePullSecrets: []
commonLabels: {}
