plugins {
    id 'com.agentengine.java-application-conventions'
    alias(libs.plugins.quarkus)
}

dependencies {
    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation libs.slf4j.api
    implementation project(':engine')
    implementation project(':engine:api')
    implementation project(':util:common')
    implementation project(':util:ms')
    implementation libs.quarkus.logging.json
    implementation libs.quarkus.rest.jackson
    implementation libs.quarkus.smallrye.openapi
    implementation libs.quarkus.mongodb.client
    implementation libs.quarkus.smallrye.health
    implementation libs.quarkus.micrometer.registry.prometheus
    implementation libs.quarkus.hibernate.validator
    implementation libs.quarkus.smallrye.fault.tolerance
    implementation libs.quarkus.grpc

    implementation libs.ag.ui.core
    implementation libs.ag.ui.server
    implementation libs.ag.ui.json
    implementation libs.ag.ui.http
    implementation libs.ag.ui.ok.http

    testImplementation libs.quarkus.junit5
    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit.jupiter
    testImplementation libs.rest.assured
    testImplementation libs.hamcrest

    integrationTestImplementation project(':engine')
    integrationTestImplementation libs.quarkus.junit5
    integrationTestImplementation libs.assertj.core
    integrationTestImplementation libs.rest.assured
    integrationTestImplementation libs.mockito.core
    integrationTestImplementation libs.testcontainers.junit.jupiter
    integrationTestImplementation libs.testcontainers.mongodb
    integrationTestImplementation libs.testcontainers.redis
}

def isCiServer = System.getenv("CI_SERVER") != null
def isCi = System.getenv("CI") != null
def isContinuousIntegration = isCiServer || isCi

if (isContinuousIntegration) {
    tasks.withType(JavaCompile) {
        options.compilerArgs += ['-Xlint:all', '-Werror']
    }
}
