plugins {
    id 'com.agentengine.java-application-conventions'
    alias(libs.plugins.quarkus)
}

dependencies {
    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation libs.slf4j.api
    implementation project(':engine')
    implementation project(':interfaces:rest')
    implementation libs.quarkus.logging.json
    implementation libs.quarkus.mongodb.client
    implementation libs.quarkus.smallrye.fault.tolerance

    testImplementation libs.quarkus.junit5
    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit.jupiter
}

tasks.named('compileJava').configure {
    dependsOn 'compileQuarkusGeneratedSourcesJava'
}
