plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation project(':util:common')
    api project(':util:pekko')
    implementation project(':util:agents')
    implementation project(':util:ms')

    api platform(libs.pekko.bom)
    api libs.pekko.actor.typed
    api libs.pekko.cluster.typed
    api libs.pekko.cluster.sharding.typed
    api libs.pekko.persistence.typed

    implementation libs.jakarta.enterprise.cdi.api
}
