{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-engine-postgres.authSecretName" . }}
  namespace: {{ include "agent-engine-postgres.namespace" . }}
  labels:
    app.kubernetes.io/name: postgres
    {{- include "agent-engine-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
