plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.scheduler'

dependencies {
    implementation project(':util:common')
    implementation project(':util:context')
    implementation project(':util:ms:client')
    compileOnly libs.mongodb.bson
    compileOnly libs.jakarta.validation.api

    implementation platform(libs.quarkus.bom)
    implementation libs.quarkus.arc
}
