plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.scheduler'

dependencies {
    implementation project(':util:common')
    implementation project(':util:ms:client')
    implementation libs.mongodb.bson
    implementation libs.jakarta.validation.api

    implementation platform(libs.quarkus.bom)
    implementation libs.quarkus.arc
}
