plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation libs.jakarta.inject.api
    implementation libs.jakarta.enterprise.cdi.api
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jackson.datatype.jdk8
    implementation libs.jackson.datatype.jsr310
    implementation libs.jackson.datatype.guava
    implementation libs.vertx.json.schema

    implementation libs.guava

    implementation libs.jinjava
    implementation libs.json.path
    implementation libs.commons.text
    implementation libs.flexmark.all
    implementation libs.slf4j.api
    implementation libs.jakarta.validation.api
    implementation libs.rxjava

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
