plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation libs.jakarta.inject.api
    implementation libs.jakarta.enterprise.cdi.api
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.vertx.json.schema

    implementation libs.guava

    implementation libs.jinjava
    implementation libs.json.path
    implementation libs.slf4j.api
    implementation libs.jakarta.validation.api

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
