plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    api libs.google.adk.core
    api project(':util:common')
    implementation project(':util:ms')
    implementation libs.microprofile.openapi.api
    implementation libs.jakarta.inject.api
    implementation libs.jakarta.enterprise.cdi.api

    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation libs.quarkus.arc
    implementation libs.jakarta.validation.api
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jinjava
    implementation libs.slf4j.api
    implementation libs.rxjava
    implementation libs.mongodb.bson
    implementation libs.json.path
    implementation libs.annotations.api
    implementation libs.stateless4j

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testImplementation libs.mockito.junit.jupiter
}
