plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    api project(':util')
    api libs.mongodb.bson
    api libs.google.adk.core
    api libs.microprofile.openapi.api
    api libs.json.path
    api libs.annotations.api
    api libs.jakarta.inject.api
    api libs.jakarta.enterprise.cdi.api
    api libs.stateless4j

    implementation(enforcedPlatform(libs.quarkus.bom))
    implementation libs.quarkus.arc
    implementation libs.jakarta.validation.api
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jinjava
    implementation libs.slf4j.api
    implementation libs.rxjava

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testImplementation libs.mockito.junit.jupiter
}
