plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    api libs.fastjson2
    api libs.mongodb.bson
    api libs.google.adk.core
    api libs.microprofile.openapi.api
    implementation libs.jackson.databind
    implementation libs.jackson.dataformat.yaml
    implementation libs.jinjava
    implementation libs.slf4j.api

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
