app-base:
  service:
    name: rest

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: rest.agent-engine.local
        paths:
          - path: /
            pathType: Prefix

  java:
    opts: "--enable-preview -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dfile.encoding=UTF-8"
    args: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=80 -XX:+ExitOnOutOfMemoryError"
