app-base:
  service:
    name: rest

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: rest.agent-engine.local
        paths:
          - path: /
            pathType: Prefix
