app-base:
  service:
    name: rest

  ingress:
    enabled: true
    className: nginx
    tlsEnabled: true
    hosts:
      - host: agents.com
        paths:
          - path: /
            pathType: Prefix
