plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.agent'

dependencies {
    api project(':tenancy:api')
    implementation project(':util:ms:client')
    api project(':util:infra')
    implementation project(':util:agents')
    implementation project(':util:common')

    api libs.reactive.streams
    api libs.jackson.databind
}
