plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation project(':util:common')
    implementation project(':util:mongodb')
    implementation libs.mongodb.bson

    implementation platform(libs.pekko.bom)
    implementation platform(libs.quarkus.bom)
    implementation libs.quarkus.arc
    implementation libs.pekko.actor.typed
    implementation libs.pekko.cluster.sharding.typed
    implementation libs.pekko.persistence.typed
    implementation libs.pekko.persistence.jdbc
    implementation libs.pekko.serialization.jackson
    implementation libs.pekko.streams
    implementation libs.rxjava

    testImplementation libs.pekko.testkit
    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
