plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation project(':engine:api')
    api libs.jakarta.inject.api

    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}
