plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation project(':engine')
    implementation project(':engine:client')
    implementation 'jakarta.inject:jakarta.inject-api:2.0.1'

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
