plugins {
    id 'com.agentengine.java-library-conventions'
}

dependencies {
    implementation project(':engine:api')
    implementation 'jakarta.inject:jakarta.inject-api:2.0.1'

    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
