replicas: 1
pdb:
  enabled: false
probes:
  liveness:
    timeoutSeconds: 10
  readiness:
    timeoutSeconds: 10
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: agent-engine-connectors
        app.kubernetes.io/instance: agent-engine-connectors
