{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-engine-rest.fullname" . }}-application-properties-configmap
  namespace: {{ include "agent-engine-rest.namespace" . }}
  labels:
    {{- include "agent-engine-rest.labels" . | nindent 4 }}
data:
  application.properties: |-
    {{- range $key, $value := .Values.config.applicationProperties }}
    {{ $key }}={{ $value }}
    {{- end }}
{{- end }}
