{{- if .Values.ingress.enabled }}
{{- $ctx := dict "root" . "component" .Values.component -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agent-engine.base.fullname" $ctx }}
  namespace: {{ include "agent-engine.base.namespace" $ctx }}
  labels:
    {{- include "agent-engine.base.labels" $ctx | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "agent-engine.base.fullname" $ctx }}
                port:
                  number: {{ $.Values.service.httpPort }}
          {{- end }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
