apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-engine-rest.fullname" . }}
  namespace: {{ include "agent-engine-rest.namespace" . }}
  labels:
    {{- include "agent-engine-rest.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agent-engine-rest.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
