plugins {
    id 'com.agentengine.java-application-conventions'
}

group = 'com.agentengine.agent'

dependencies {
    implementation project(':agent:api')
    implementation project(':util:ms:client')
    implementation project(':util:infra')
    implementation project(':agent:infra')
    implementation project(':util:models')
    implementation project(':util:vectordb')
    implementation project(':knowledge:api')
    implementation project(':catalog:api')
    implementation project(':util:common')
    implementation project(':util:pekko')
    implementation project(':util:agents')
    runtimeOnly project(':util:ms:server')
    implementation project(':connectors:api')
    implementation project(':util:cloudstorage')

    implementation libs.google.adk

    implementation platform(libs.pekko.bom)
    implementation libs.pekko.actor.typed
    implementation libs.pekko.cluster.typed
    implementation libs.pekko.cluster.sharding.typed
    implementation libs.pekko.persistence.typed
    runtimeOnly libs.pekko.persistence.jdbc
    implementation libs.pekko.streams.typed
    runtimeOnly libs.pekko.serialization.jackson

    runtimeOnly libs.postgresql


    implementation platform(libs.quarkus.bom)
    implementation libs.quarkus.arc
    implementation libs.quarkus.hibernate.validator
    implementation libs.quarkus.logging.json
    implementation libs.quarkus.opentelemetry
    implementation libs.quarkus.smallrye.health

    implementation libs.slf4j.api
    implementation libs.flexmark.all
    implementation libs.commonmark
    implementation libs.guava
    implementation libs.rxjava
    implementation libs.stateless4j

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit.jupiter
}
