{{- if eq (.Values.type | default "deployment") "statefulset" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-engine.app-base.instance" . }}-internal
  namespace: {{ include "agent-engine.app-base.namespace" . }}
  labels:
    {{- include "agent-engine.app-base.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  selector:
    {{- include "agent-engine.app-base.selectorLabels" . | nindent 4 }}
  ports:
    - name: pekko
      port: {{ .Values.service.pekkoPort }}
      targetPort: pekko
{{- end }}
