{{- if include "agent-engine.app-base.needsRbac" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent-engine.app-base.instance" . }}
  namespace: {{ include "agent-engine.app-base.namespace" . }}
  labels:
    {{- include "agent-engine.app-base.labels" . | nindent 4 }}
rules:
{{- include "agent-engine.app-base.rbacRules" . | nindent 2 }}
{{- end }}
