apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-engine.app-base.instance" . }}
  namespace: {{ include "agent-engine.app-base.namespace" . }}
  labels:
    {{- include "agent-engine.app-base.labels" . | nindent 4 }}
automountServiceAccountToken: {{ include "agent-engine.app-base.automountToken" . }}
