apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: {{ include "agent-engine.infra-base.namespace" . }}
  labels:
    {{- include "agent-engine.infra-base.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "persistence.size must be set" .Values.persistence.size }}
