plugins {
    id 'com.agentengine.java-application-conventions'
}

group = 'com.agentengine.knowledge'

dependencies {
    implementation project(':knowledge:api')
    implementation project(':util:common')
    implementation project(':util:agents')
    implementation project(':util:mongodb')
    implementation project(':util:vectordb')
    implementation project(':util:ms')
    implementation project(':catalog:api')
    implementation project(':connectors:api')
    implementation project(':agent:infra')
    implementation project(':util:cloudstorage')

    implementation platform(libs.langchain4j.bom)
    implementation platform(libs.quarkus.bom)

    implementation libs.langchain4j.core
    implementation libs.quarkus.mongodb.client
    implementation libs.quarkus.arc
    implementation libs.quarkus.hibernate.validator
    implementation libs.quarkus.opentelemetry
    implementation libs.quarkus.smallrye.health

    implementation libs.jakarta.inject.api
}
