plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.connectors'

dependencies {
    implementation project(':connectors:api')
    implementation libs.jackson.databind
    implementation libs.slf4j.api
    implementation libs.jakarta.inject.api
    implementation libs.jakarta.enterprise.cdi.api
}
