plugins {
    id 'java'
    id 'java-gradle-plugin'
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation libs.spotless.gradle.plugin
    implementation libs.jandex.gradle.plugin
}

gradlePlugin {
    plugins {
        javaLibraryConventions {
            id = 'com.agentengine.java-library-conventions'
            implementationClass = 'com.agentengine.conventions.JavaLibraryConventionsPlugin'
        }
        javaApplicationConventions {
            id = 'com.agentengine.java-application-conventions'
            implementationClass = 'com.agentengine.conventions.JavaApplicationConventionsPlugin'
        }
    }
}
