agentengine.log.level=DEBUG

quarkus.log.level=INFO
quarkus.log.console.level=${agentengine.log.level}
quarkus.log.category."com.agentengine".level=${agentengine.log.level}

# Use external MongoDB instead of Quarkus dev services.
quarkus.mongodb.devservices.enabled=false
quarkus.mongodb.connection-string=mongodb://localhost:27018

# File JSON
quarkus.log.file.enable=true
quarkus.log.file.path=logs/agent-engine.log
quarkus.log.file.level=${agentengine.log.level}
quarkus.log.file.json=true

# OpenAPI
quarkus.smallrye-openapi.store-schema-directory=build/openapi
quarkus.smallrye-openapi.store-schema-file-name=agent-engine
