quarkus.log.level=DEBUG
quarkus.log.category."com.agentengine".level=DEBUG
quarkus.log.category."com.agentengine.interfaces.rest.handlers.AGUIEventMapper".level=DEBUG
quarkus.log.category."com.agentengine.engine.agents".level=DEBUG
quarkus.log.category."com.agentengine.engine.repository".level=DEBUG

# Use external MongoDB instead of Quarkus dev services.
quarkus.mongodb.devservices.enabled=false

# File JSON
quarkus.log.file.enable=true
quarkus.log.file.path=logs/agent-engine.log
quarkus.log.file.level=DEBUG
quarkus.log.file.json=true

# OpenAPI
quarkus.smallrye-openapi.store-schema-directory=build/openapi
quarkus.smallrye-openapi.store-schema-file-name=agent-engine
