package com.agentengine.util.vectordb;

import com.agentengine.util.common.beans.BaseEntity;
import java.util.HashMap;
import java.util.Map;

/**
 * Base class for entities stored in a vector store.
 *
 * <p>Supports multiple named vector fields per entity, each potentially generated by a different
 * embedding model. The field name follows the {@code <logicalField>Vector} convention established
 * by {@link VectorStore} (e.g. logical field {@code "text"} → physical vector field
 * {@code "textVector"}).
 *
 * <p>Concrete subclasses declare which logical fields they index and populate vectors accordingly.
 * A subclass with a single vector field is simply a degenerate case of this model.
 */
public abstract class VectorEntity extends BaseEntity {

    /** Named vectors keyed by physical vector field name (e.g. {@code "textVector"}). */
    private Map<String, float[]> vectors;

    public Map<String, float[]> getVectors() {
        return vectors;
    }

    public void setVectors(final Map<String, float[]> vectors) {
        this.vectors = vectors;
    }

    /**
     * Sets a single named vector, initialising the map on first use.
     *
     * @param field  physical vector field name (e.g. {@code "textVector"})
     * @param vector the embedding
     */
    public void setVector(final String field, final float[] vector) {
        if (this.vectors == null) {
            this.vectors = new HashMap<>();
        }
        this.vectors.put(field, vector);
    }

    /**
     * Returns the vector for the given physical field name, or {@code null} if absent.
     *
     * @param field physical vector field name (e.g. {@code "textVector"})
     */
    public float[] getVector(final String field) {
        return vectors == null ? null : vectors.get(field);
    }
}
