apiVersion: v2
name: agent-engine-connectors
description: Connectors service chart for Agent Engine
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: app-base
    version: 0.1.0
    repository: "file://../app-base"
