plugins {
    id 'com.agentengine.java-application-conventions'
}

group = 'com.agentengine.connectors'

dependencies {
    implementation project(':connectors:api')
    implementation project(':connectors:infra')
    implementation project(':connectors:http')
    implementation project(':util:common')
    implementation project(':util:ms:server')

    implementation platform(libs.quarkus.bom)
    implementation libs.quarkus.arc
    implementation libs.quarkus.hibernate.validator
    implementation libs.quarkus.logging.json
    implementation libs.quarkus.opentelemetry
    implementation libs.quarkus.smallrye.health

    implementation libs.jackson.databind
    implementation libs.jakarta.enterprise.cdi.api
    implementation libs.jakarta.inject.api
    implementation libs.slf4j.api
    implementation libs.groovy
    implementation libs.okhttp

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit.jupiter
    testImplementation libs.okhttp.mockwebserver
}
