plugins {
    id 'com.agentengine.java-library-conventions'
}

group = 'com.agentengine.connectors'

dependencies {
    implementation project(':util:common')
    implementation project(':util:mongodb')
    implementation libs.jackson.databind
    implementation libs.jakarta.enterprise.cdi.api
    implementation libs.mongodb.driver.sync
    implementation libs.jakarta.validation.api
    implementation libs.jakarta.inject.api
    implementation libs.slf4j.api
    implementation libs.groovy
    implementation libs.okhttp

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit.jupiter
    testImplementation libs.okhttp.mockwebserver
}
